"""empty message

Revision ID: 1d7d173b82b6
Revises: f2786daa4f62
Create Date: 2023-10-16 23:21:18.620561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1d7d173b82b6'
down_revision: Union[str, None] = 'f2786daa4f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("('')"), nullable=False))
    op.add_column('user', sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'enabled')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
